---
- hosts: all
  tasks:
    - debug: msg="Test!"
    - fail:
        msg: "testing failed delete"
      when:
        - error_on_delete | default(false)
        - (cluster_state|default("present")) == "absent"
    - ansible.builtin.command: "ssh test@login-cpu.hpc.cam.ac.uk"
